# Generated by Django 4.2.7 on 2023-11-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverynotice_orderconfirmation_quotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_notice',
        ),
    ]
