# Generated by Django 4.2.7 on 2023-11-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_invoice_order_order_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_file',
            new_name='filepath',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
