# Generated by Django 4.2.7 on 2023-11-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_delivery_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prev_status',
            field=models.IntegerField(choices=[(1, 'Deal Closed'), (2, 'Quotation Sent'), (3, 'Order Confirmation Sent'), (4, 'Invoice Sent'), (5, 'Delivery Scheduled'), (6, 'Delivery Confirmed')], default=1),
        ),
    ]
