# Generated by Django 4.2.7 on 2023-11-09 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_deal_close_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('cvr_number', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('po_number', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_file', models.FilePathField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('pipedrive_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('pipedrive_meta', models.JSONField()),
                ('order_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Stock',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='deal',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
