# Generated by Django 4.2.7 on 2023-11-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invoice_currency_invoice_line_items_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
