# Generated by Django 4.2.7 on 2023-11-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_delivery_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='vat_amt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='VAT (%)'),
        ),
    ]
