# Generated by Django 4.2.7 on 2023-11-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_invoice_iban_remove_invoice_swift_bic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Deal Closed'), (2, 'Quotation Sent'), (3, 'Order Confirmation Sent'), (4, 'Invoice Sent'), (5, 'Delivery Scheduled'), (6, 'Delivery Confirmed')], default=1, max_length=50),
        ),
    ]
