# Generated by Django 4.2.7 on 2023-11-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_invoice_vat_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='line_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
