# Generated by Django 4.2.7 on 2023-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotation_contact_email_quotation_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
