# Generated by Django 4.2.7 on 2023-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_quotation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sender_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sender_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
