# Generated by Django 4.2.7 on 2023-11-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
