# Generated by Django 4.2.7 on 2023-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
