# Generated by Django 4.2.7 on 2023-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_contact_email_order_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='sent date'),
        ),
    ]
