# Generated by Django 4.2.7 on 2023-11-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_purchaseorder_order_order_purchase_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_file',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='filepath',
            field=models.FilePathField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(null=True),
        ),
    ]
