# Generated by Django 4.2.7 on 2023-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_purchaseorder_po_file_purchaseorder_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prev_status',
            field=models.IntegerField(choices=[(1, 'Quotation Sent'), (2, 'Purchase Order Received'), (3, 'Order Confirmation Sent'), (4, 'Invoice Sent'), (5, 'Delivery Scheduled'), (6, 'Delivery Confirmed')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Quotation Sent'), (2, 'Purchase Order Received'), (3, 'Order Confirmation Sent'), (4, 'Invoice Sent'), (5, 'Delivery Scheduled'), (6, 'Delivery Confirmed')], default=1),
        ),
    ]
