# Generated by Django 4.2.7 on 2023-11-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
