# Generated by Django 4.2.7 on 2023-11-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_deliverynotice_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynotice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='deliverynotice',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='deliverynotice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_vat',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='vat_amt',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='total_vat',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='orderconfirmation',
            name='vat_amt',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='line_items',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='total_vat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.FloatField(blank=True, default=25, null=True, verbose_name='VAT (%)'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
