# Generated by Django 4.2.7 on 2023-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_last_updated_order_status_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prev_status_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
