# Generated by Django 4.2.7 on 2023-12-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_order_total_vat_remove_order_vat_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='IBAN',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SWIFT_BIC',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='po_number',
        ),
    ]
